#Configuration File for CodeCov
coverage:
  status:
    project:
      default:
        informational: true
        target: auto
        threshold: 0%
        base: auto
        paths:
          - "include"
          - "python"
          - "src"
          - "tools"
    patch:
      default:
        informational: true
        target: auto
        threshold: 0%
        base: auto
        paths:
          - "include"
          - "python"
          - "src"
          - "tools"
comment:
  behavior: new

# Suggested workaround to fix "missing base report" issue when using Squash and
# Merge Strategy in GitHub. See this comment from CodeCov support about this
# undocumented option:
# https://community.codecov.io/t/unable-to-determine-a-parent-commit-to-compare-against-in-base-branch-after-squash-and-merge/2480/15
codecov:
  allow_coverage_offsets: true
