# Copyright (c) 2023, NVIDIA CORPORATION.

repos:
      - repo: https://github.com/rapidsai/dependency-file-generator
        rev: v1.13.11
        hooks:
            - id: rapids-dependency-file-generator
              args: ["--clean"]
      - repo: https://github.com/PyCQA/isort
        rev: 5.12.0
        hooks:
              - id: isort
                args: ["--settings-file=./python/setup.cfg"]
                files: ^python/
      - repo: https://github.com/PyCQA/flake8
        rev: 6.1.0
        hooks:
              - id: flake8
                args: ["--config=./python/setup.cfg"]
                files: ^python/
      - repo: https://github.com/google/yapf
        rev: v0.40.2
        hooks:
              - id: yapf
                args: ["--style", "./python/setup.cfg"]
                files: ^python/

default_language_version:
      python: python3
