# SPDX-FileCopyrightText: Copyright (c) 2022-2024, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{% set version = environ.get('GIT_VERSION', '0.0.0.dev').lstrip('v') + environ.get('VERSION_SUFFIX', '') %}
{% set py_version = environ.get('CONDA_PY', '3.10') %}
{% set cuda_version = '.'.join(environ.get('CUDA', '12.5').split('.')[:2]) %}

package:
  name: libmrc-split
  version: {{ version }}

source:
  git_url: ../../../..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  script_env:
    - CMAKE_CUDA_ARCHITECTURES=RAPIDS
    - MRC_CACHE_DIR
    - PARALLEL_LEVEL
  include_recipe: False

requirements:
  build:
    # Requirements that are only necessary for build or would be different when cross compiling. Keep sorted!
    - {{ compiler("c") }}
    - {{ compiler("cuda") }}
    - {{ compiler("cxx") }}
    - ccache
    - cmake =3.27
    - libtool
    - ninja =1.11
    - numactl =2.0.18
    - pkg-config =0.29
    - sysroot_linux-64 >=2.28
  host:
    # Libraries necessary to build. Keep sorted!
    - boost-cpp =1.84
    - cuda-cudart-dev {{ cuda_version }}.*
    - cuda-nvml-dev {{ cuda_version }}.*
    - cuda-nvrtc-dev {{ cuda_version }}.*
    - cuda-version {{ cuda_version }}.*
    - doxygen 1.10.0
    - glog>=0.7.1,<0.8
    - libgrpc =1.62.2
    - gtest =1.14
    - libhwloc =2.9.2
    - librmm {{ rapids_version }}
    - nlohmann_json =3.11
    - pybind11-abi # See: https://conda-forge.org/docs/maintainer/knowledge_base.html#pybind11-abi-constraints
    - pybind11-stubgen =2.4.2
    - python {{ python }}
    - scikit-build =0.17
    - ucx =1.15

outputs:
  - name: libmrc
    build:
      string: cuda_{{ cuda_version }}_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}
      run_exports:
        - {{ pin_subpackage("libmrc", max_pin="x.x") }}
      include_recipe: False
    script: move_libmrc_files.sh
    requirements:
      build:
        # Most are copied from the split package to utilize the run_exports. Keep sorted!
        - {{ compiler("c") }}
        - {{ compiler("cuda") }}
        - {{ compiler("cxx") }}
        - cmake =3.27
        - numactl =2.0.18
        - sysroot_linux-64 >=2.28
      host:
        # Any libraries with weak run_exports need to go here to be added to the run. Keep sorted!
        - boost-cpp =1.84
        - cuda-version # Needed to allow pin_compatible to work
        - glog>=0.7.1,<0.8
        - libgrpc =1.62.2
        - libhwloc =2.9.2
        - librmm {{ rapids_version }}
        - nlohmann_json =3.11
        - ucx =1.15
      run:
        # Manually add any packages necessary for run that do not have run_exports. Keep sorted!
        - cuda-version {{ cuda_version }}.*
        - nlohmann_json =3.11
        - ucx =1.15
        - cuda-cudart
        - boost-cpp =1.84
    test:
      script: test_libmrc.sh
      files:
        - build/**/*.x

  - name: mrc
    build:
      string: cuda_{{ cuda_version }}_py{{ py_version }}_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}
      run_exports:
        - {{ pin_subpackage("mrc", max_pin="x.x") }}
      ignore_run_exports:
        - pypy
      missing_dso_whitelist:
        - $RPATH/ld-linux-x86-64.so.2 # From python
        - $RPATH/libc.so.6 # From python
        - $RPATH/libpthread.so.0 # Sample modules
      include_recipe: False
    script: move_mrc_files.sh
    requirements:
      host:
        # Only should need libmrc and python. Keep sorted!
        - {{ pin_subpackage('libmrc', exact=True) }}
        - python {{ python }}
      run:
        - {{ pin_subpackage('libmrc', exact=True) }}
        - rmm {{ rapids_version }}.* # This is not necessary but required until this is fixed: https://github.com/mamba-org/boa/issues/232
        - python
    test:
      imports:
        - mrc
      script: test_mrc.sh
      source_files:
        # Copy the pytest source files
        - python/pytest.ini
        - python/setup.cfg
        - python/tests/*
      requires:
        - numpy
        - nvtx
        - pytest
        - cuml {{ rapids_version }}.* # Ensure we can install cuml. This can cause issues solving libabseil

about:
  home: https://github.com/nv-morpheus/MRC
  license_family: Apache
  license_file: LICENSE
  license: Apache-2.0
  summary: A GPU accelerated streaming data library with python bindings
