#!/bin/bash
# SPDX-FileCopyrightText: Copyright (c) 2021-2022,NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#
# Based on the pre-commit.sample script included in git

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
source ${SCRIPT_DIR}/../scripts/common.sh

if git rev-parse --verify HEAD >/dev/null 2>&1
then
   GIT_DIFF_BASE=HEAD
else
   # Initial commit: diff against an empty tree object
   GIT_DIFF_BASE=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

function run_and_check() {
   CMD=$1
   OUT=$(${CMD} 2>&1)
   RET_VAL=$?
   if [ "$RET_VAL" != "0" ]; then
      echo -e "${OUT}"
   fi
}

export CHANGED_FILES=$(GIT_DIFF_ARGS="--cached --name-only" get_modified_files)

if [[ "${CHANGED_FILES}" != "" ]]; then
   run_and_check "python3 ci/scripts/copyright.py --git-diff-staged --update-current-year --verify-apache-v2 --git-add"
   SKIP_CLANG_TIDY=1 SKIP_IWYU=1 run_and_check "ci/scripts/cpp_checks.sh"
fi
